/*
 * Logger.h
 *
 *  Created on: 26 May 2022
 *      Author: Mustafa Malik
 *      Copyright Notice: Copyright (C) 2022, Mustafa Malik
 *      Comment generated by: Eclipse IDE for C/C++ Developers
 */

#ifndef HEADERS_LOGGER_H_
#define HEADERS_LOGGER_H_

#include <iostream>

#define print(x) std::cout << x << '\n';

#define LOG_LEVEL_INFO 0x0
#define LOG_LEVEL_NORM 0x1
#define LOG_LEVEL_WARN 0x2
#define LOG_LEVEL_ERROR 0x3

using std::string;

class Log {
private:
	int m_lvl;
public:
	string message;
public:
	void setLevel(int lvl) {
		m_lvl = lvl;
	}
	void setMessage(string m) {
		message = m;
	}
	void log() {
		switch (m_lvl) {
		case LOG_LEVEL_INFO: print(">> [INFO]: " + message) break;
		case LOG_LEVEL_NORM: print(">> [NORMAL]: " + message) break;
		case LOG_LEVEL_WARN: print(">> [WARNING]: " + message) break;
		case LOG_LEVEL_ERROR: print(">> [ERROR]: " + message) break;
		}
	}
};



#endif /* HEADERS_LOGGER_H_ */
